config/routes.rb
Rails.application.routes.draw do
  resources :technical_words do
    collection do
      post :relation_words      
    end
  end
end

app/models/technical_word.rb
class TechnicalWord < ActiveRecord::Base
end

app/models/technical_word_relation.rb
class TechnicalWordRelation < ActiveRecord::Base
  belongs_to :technical_word
  belongs_to :source, class_name: 'TechnicalWord', foreign_key: :source_word_id
  belongs_to :target, class_name: 'TechnicalWord', foreign_key: :target_word_id
  
  def self.relation_words(technical_word)
    source_words = TechnicalWordRelation.includes(:source).includes(:target).where(source_word_id: technical_word.id).map do |word|
      { source_id: word.source.id, source: word.source.name, target_id: word.target.id, target: word.target.name}
    end
    target_words = TechnicalWordRelation.includes(:source).includes(:target).where(target_word_id: technical_word.id).map do |word|
      { source_id: word.source.id, source: word.source.name, target_id: word.target.id, target: word.target.name}
    end
    return source_words + target_words
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/technical_words_controller.rb
class TechnicalWordsController < ApplicationController
  before_action :set_technical_word, only: [:show, :edit, :update, :destroy]

  # GET /technical_words
  # GET /technical_words.json
  def index
    @technical_words = TechnicalWord.all
  end

  # GET /technical_words/1
  # GET /technical_words/1.json
  def show
  end

  # GET /technical_words/new
  def new
    @technical_word = TechnicalWord.new
  end

  # GET /technical_words/1/edit
  def edit
  end

  # POST /technical_words
  # POST /technical_words.json
  def create
    @technical_word = TechnicalWord.new(technical_word_params)

    respond_to do |format|
      if @technical_word.save
        format.html { redirect_to @technical_word, notice: 'Technical word was successfully created.' }
        format.json { render :show, status: :created, location: @technical_word }
      else
        format.html { render :new }
        format.json { render json: @technical_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /technical_words/1
  # PATCH/PUT /technical_words/1.json
  def update
    respond_to do |format|
      if @technical_word.update(technical_word_params)
        format.html { redirect_to @technical_word, notice: 'Technical word was successfully updated.' }
        format.json { render :show, status: :ok, location: @technical_word }
      else
        format.html { render :edit }
        format.json { render json: @technical_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /technical_words/1
  # DELETE /technical_words/1.json
  def destroy
    @technical_word.destroy
    respond_to do |format|
      format.html { redirect_to technical_words_url, notice: 'Technical word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def relation_words
    technical_word_name = TechnicalWord.where(name: params[:technical_word_name]).first
    if technical_word_name
      render json: { relation_words: TechnicalWordRelation.relation_words(technical_word_name) }
    else
      render json: { relation_words: '' }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technical_word
      @technical_word = TechnicalWord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technical_word_params
      params.require(:technical_word).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/technical_words_helper.rb
module TechnicalWordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>D3Rails</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body ng-app='D3Rails'>
<%= yield %>
</body>
</html>

app/views/technical_words/_form.html.erb
<%= form_for(@technical_word) do |f| %>
  <% if @technical_word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@technical_word.errors.count, "error") %> prohibited this technical_word from being saved:</h2>

      <ul>
      <% @technical_word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/technical_words/edit.html.erb
<h1>Editing Technical Word</h1>

<%= render 'form' %>

<%= link_to 'Show', @technical_word %> |
<%= link_to 'Back', technical_words_path %>

app/views/technical_words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Technical Words</h1>

<div ng-controller='TechnicalWordCtrl'>
  <div>
    <input maxlength="20" name="relation_base_word" ng-model="relationBaseWord" placeholder="検索したいトレンドワードを入力してください" size="40" type='text' />
  </div>
  <div class="col-sm-12 alert alert-danger" ng-show="relatinSearchFail">
    {{ relationBaseWord }} は存在しません
  </div>
  <div d3-graph relatin_search_fail="relatinSearchFail" relation_base_word="relationBaseWord"></div>
</div>

<%= link_to 'New Technical word', new_technical_word_path %>

app/views/technical_words/new.html.erb
<h1>New Technical Word</h1>

<%= render 'form' %>

<%= link_to 'Back', technical_words_path %>

app/views/technical_words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @technical_word.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @technical_word.description %>
</p>

<%= link_to 'Edit', edit_technical_word_path(@technical_word) %> |
<%= link_to 'Back', technical_words_path %>